apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: new-test
  description: An example of a Backstage application.
  annotations:
    backstage.io/kubernetes-id: jenkins-operator
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
